CREATE DATABASE Library;

CREATE TABLE books(-- THERE ARE TWO FOREIGN KEYS FROM BOOKS AND PUBLISHER
    Title VARCHAR(100)NOT NULL,
	Edition VARCHAR(100),
    Year_of_publication DATE,
	Price INT,
    ISBN INT PRIMARY KEY 
);
CREATE TABLE Copies(-- THERE ARE FOREIGN KEY FROM BOOKS TABLE
    Copy_ID INT PRIMARY KEY,
	Copy_number INT,
	availabe VARCHAR(10),
	Borrowing_Period INT,
	ISBN INT FOREIGN KEY  REFERENCES  books(ISBN)
);
CREATE TABLE Borrowere(--THERE ARE TWO FOREIGN KEYS FROM COPY TABLE AND PHONE_BORROWERE TABLE
    Brr_ID INT PRIMARY KEY ,
	Brr_Name VARCHAR(100)NOT NULL,
	Brr_address VARCHAR(100),
);
CREATE TABLE Category(
   Cat_ID INT PRIMARY KEY,
   Cat_Name VARCHAR(100)NOT NULL
);
CREATE TABLE Author(-- THRERE ARE FOREIGN KEY FROM NAME TABLE
   Au_ID INT PRIMARY KEY ,
   First_Name VARCHAR(100),
   Mid_Name VARCHAR(100),
   Last_Name VARCHAR(100)
);
CREATE TABLE Publisher(--THERE ARE FOREIGN FROM PHONE PUBLISHER TABLE
   Pub_ID INT PRIMARY KEY NOT NULL,
   Pub_Name VARCHAR(100),
   Pub_Address VARCHAR(100) 
);
CREATE TABLE Borrow(-- RELATIONSHIP BETWEEN BORROWERE TABLE AND COPIES
   borrowing_date DATE,
   return_date DATE,
   Borrowere_ID INT FOREIGN KEY  REFERENCES Borrowere(Brr_ID),--FROM BOOK TABLE
   Copy_ID INT FOREIGN KEY  REFERENCES Copies(Copy_ID)-- FROM COPY TABLE
);
CREATE TABLE Authorithies(--RELATIONSHIP TABLE BETWEEN AUTHOR AND BOOK
   Author_ID INT FOREIGN KEY  REFERENCES Author(Au_ID),
   ISBN INT FOREIGN KEY  REFERENCES books(ISBN)
);
CREATE TABLE Phone_Borowere(
   Brr_Phone VARCHAR(100),
   Brr_number INT FOREIGN KEY REFERENCES Borrowere(Brr_ID)  
);
CREATE TABLE Phone_Publisher(--FOR TABLE PUBLISHER
   Pub_ID INT FOREIGN KEY  REFERENCES  Publisher(Pub_ID),
   Phone_Number  VARCHAR(50)
);
